routes/admin.php
<?php

Route::get('login', ['as' => 'login', 'uses' => 'AuthController@getLogin']);
Route::post('login', ['as' => 'login', 'uses' => 'AuthController@postLogin']);
Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@getLogout']);


Route::group(['middleware' => 'auth:admin'], function() {
    // Dashboard
    Route::get('/', ['as' => 'home.index', 'uses' => 'HomeController@index']);

    // Admin
    Route::get('/admin-datatable',['as' => 'admin.datatable', 'uses' =>  'AdminController@adminsList']);
    Route::resource('admin', 'AdminController');
    
    // Users
    Route::get('/user-datatable',['as' => 'user.datatable', 'uses' =>  'UserController@usersList']);
    Route::resource('user', 'UserController');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/include/datatable/action_button.blade.php
<div class="btn-group">
	{{ Form::open(['route' => [$routePrefix . '.edit', $model->id],  'method' => 'GET']) }}
	<button type="submit" class="btn btn-primary">
		<i class="glyphicon" aria-hidden="true"></i> Düzenle
    </button>
	{{ Form::close() }}
{{ Form::open(['route' => [$routePrefix . '.destroy', $model->id],  'method' => 'DELETE']) }}
	<button type="submit" class="btn btn-primary">
		<i class="glyphicon" aria-hidden="true"></i> Sil
	</button>
{{ Form::close() }}
</div>

resources/views/admin/include/datatable/index.blade.php
<div class="right_col" role="main">
  <div class="container">
    <h2>DataTable</h2>
          <div style="display: flex; justify-content: flex-end">
              <div class="btn-group">
                  <a href="{{ route('admin.admin.create')}}" class="btn btn-primary active">
                      <i class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></i> Oluştur
                  </a>
              </div>
          </div>
          <table class="table table-bordered" id="laravel_datatable">
      <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Email</th>
          <th>Created at</th>
          <th>Action</th>
        </tr>
      </thead>
    </table>
  </div>
</div>